// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIhYs0fWwOigO2WWt8wQ55Efx5bMfpFWw',
    appId: '1:962764262859:web:9e9815771c2d6424d47a4e',
    messagingSenderId: '962764262859',
    projectId: 'fir-flutter-57563',
    authDomain: 'fir-flutter-57563.firebaseapp.com',
    storageBucket: 'fir-flutter-57563.appspot.com',
    measurementId: 'G-0CBN21H9D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBth7-Lc2DMw9K0Bl-__psNWI8FGwRQuls',
    appId: '1:962764262859:android:4259dfa0e81c4b77d47a4e',
    messagingSenderId: '962764262859',
    projectId: 'fir-flutter-57563',
    storageBucket: 'fir-flutter-57563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vSojDEkiAzXURcgc82xV2R-btkwSmQs',
    appId: '1:962764262859:ios:9b7677fff20f0ae2d47a4e',
    messagingSenderId: '962764262859',
    projectId: 'fir-flutter-57563',
    storageBucket: 'fir-flutter-57563.appspot.com',
    iosClientId: '962764262859-gi8nboie84068gbmb9vgooi27ik1maid.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vSojDEkiAzXURcgc82xV2R-btkwSmQs',
    appId: '1:962764262859:ios:9b7677fff20f0ae2d47a4e',
    messagingSenderId: '962764262859',
    projectId: 'fir-flutter-57563',
    storageBucket: 'fir-flutter-57563.appspot.com',
    iosClientId: '962764262859-gi8nboie84068gbmb9vgooi27ik1maid.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
